### ISSUE TITLE
Weiterleitung

### ISSUE THREAD

**Issue by Witti2** [euler271/news-to-newsletter-bundle#2]
Es wird bei der Konfiguration die dort angebenen Weiterleitungsseite ignoriert. 

PS. Außerdem ist es nicht sofort für den Kunden ersichtlich ob der Versand geklappt hat, das wenn die eingebaute Bestätigung angezeigt wird, das Formular trotzdem zu sehen ist. Was bei uns dazu geführt hat, das sich die Kunden teilweise mehrfach über unterschidliche Mails anmelden, bzw. wir Hinweise bekommen, das die Anmeldung nicht funktioniert hat. Wir haben uns erst einmal damit beholfen, den Hinweis in orange etwas auffälliger zu gestellten, damit dieser nicht übersehen wird. Evtl. wäre es ja möglich nach dem Absenden wenn die Erfolgsmeldung angezeigt wird, das Formular zu verstecken, oder eben die Weiterleitung funktionell machen.

Grüße

**Comment by euler271** [comment]
Die Weiterleitung funktioniert nun im neuesten release Ordnungsgemäß.

**Comment by Witti2** [comment]
Hallo, besten Dank. Wann kann man das neueste Release denn über den Manager updaten? bisher wird noch kein neues Release angezeigt.

Grüße
